spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/moodapp
spring.datasource.username=root
spring.datasource.password=Sarthak

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true